export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const GET_NOTES = 'GET_NOTES';
export const GET_NOTES_WATCHER = 'GET_NOTES_WATCHER';
export const ADD_NOTE_WATCHER = 'ADD_NOTE_WATCHER';
export const DELETE_NOTE_WATCHER ='DELETE_NOTE_WATCHER';
